name: Github Actions Demo
on: [push]
jobs:
  check-github-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "trigged by ${{ github.event_name }} event"
      - run: echo "running on a ${{ runner.os }} server hosted by Github"
      - name: check out repo code
        uses: actions/checkout@v2
      - run: echo "the ${{ github.repository }} has been cloned"
      - name: list files in the repo
        run: |
          ls ${{ github.workspace }}