name: Test secret and ssh action
on: [push]

jobs:
  SECRET-SSH-ACTIONS:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          passwork: ${{ secrets.SSH_PWD }}
          script_stop: true
          script: |
            pwd
            ls -l
            touch secret.txt
            echo ${{ secrets.MYSECRET }} >> secret.txt
            cat secret.txt

